[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x505050"
blue = "0x61afef"
cyan = "0x35a77c"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xe5c07b"


[colors.normal]
black = "0x202020"
blue = "0x61afef"
cyan = "0x35a77c"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xc7c7c7"
yellow = "0xe5c07b"


[colors.primary]
background = "0x000000"
foreground = "0xfafafa"

[font]
size = 13

[font.bold]
family = "jetbrains mono nerd font"
style = "bold"

[font.bold_italic]
family = "jetbrains mono nerd font"
style = "bolditalic"

[font.italic]
family = "jetbrains mono nerd font"
style = "italic"

[font.normal]
family = "jetbrains mono nerd font"
style = "regular"

[window]
padding = {x = 20, y= 20}


